// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAinZPhMSaqEf_K70wHrN-k2qMTqk1sLtw',
    appId: '1:755371683952:web:58f703c6aa4f41b5d484b5',
    messagingSenderId: '755371683952',
    projectId: 'react-foodordering-app-a95e5',
    authDomain: 'react-foodordering-app-a95e5.firebaseapp.com',
    databaseURL:
        'https://react-foodordering-app-a95e5-default-rtdb.firebaseio.com',
    storageBucket: 'react-foodordering-app-a95e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDumSLVDDV01cJ0yX9d0WFZqasr6oIB7CU',
    appId: '1:755371683952:android:bbd4dca92dae5e9cd484b5',
    messagingSenderId: '755371683952',
    projectId: 'react-foodordering-app-a95e5',
    databaseURL:
        'https://react-foodordering-app-a95e5-default-rtdb.firebaseio.com',
    storageBucket: 'react-foodordering-app-a95e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCry7tsJrXS2CWWyLovL4cO_8a4ZIk7ThU',
    appId: '1:755371683952:ios:e668add930c17b6fd484b5',
    messagingSenderId: '755371683952',
    projectId: 'react-foodordering-app-a95e5',
    databaseURL:
        'https://react-foodordering-app-a95e5-default-rtdb.firebaseio.com',
    storageBucket: 'react-foodordering-app-a95e5.appspot.com',
    iosClientId:
        '755371683952-as1e4auk07qqeqbggi0kdp0rqp56p32e.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmPushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCry7tsJrXS2CWWyLovL4cO_8a4ZIk7ThU',
    appId: '1:755371683952:ios:e668add930c17b6fd484b5',
    messagingSenderId: '755371683952',
    projectId: 'react-foodordering-app-a95e5',
    databaseURL:
        'https://react-foodordering-app-a95e5-default-rtdb.firebaseio.com',
    storageBucket: 'react-foodordering-app-a95e5.appspot.com',
    iosClientId:
        '755371683952-as1e4auk07qqeqbggi0kdp0rqp56p32e.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcmPushNotifications',
  );
}
